GET http://localhost:3000/orders

###

61ccc3893fd583d64a3a7035
61ccc40d05fd8b99c97aff09
61ccc65e8aa921f778052c39
61ccc65f8aa921f778052c3b

###

GET http://localhost:3000/orders/61ccc65e8aa921f778052c39

###

POST http://localhost:3000/orders
Content-Type: application/json

{
    "nameClient": "Med Ebabe",
    "nameOrder": "crep house wrap",
    "priceOrder": "5000",
    "imageOrder": "https://images.unsplash.com/photo-1598679253544-2c97992403ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"
}

###

DELETE http://localhost:3000/orders/61ccc65e8aa921f778052c39

###

PATCH http://localhost:3000/orders/61ccc3893fd583d64a3a7035
Content-Type: application/json

{

    "nameClient": "kossovy"

}